image: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.1-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t dubzland-ntp tests/
    - docker run dubzland-ntp /usr/src/dubzland-ntp/tests/run_tests.sh
